name: Executar notebook BAT

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.API_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
jobs:
  run-bat-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter

      - name: Executar notebook
        run: |
          jupyter nbconvert --to notebook --execute bat_tracker.ipynb --output executed_bat_tracker.ipynb
